# Generated by Django 5.1.2 on 2026-01-03 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('social_security_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership')], max_length=20)),
                ('work_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('original_hire_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('TEMPORARY', 'Temporary'), ('SEASONAL', 'Seasonal'), ('CONSULTANT', 'Consultant'), ('FREELANCER', 'Freelancer')], max_length=50)),
                ('position_title', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=100)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('job_level', models.CharField(blank=True, max_length=50, null=True)),
                ('job_family', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_work_eligible', models.BooleanField(default=False)),
                ('remote_work_percentage', models.IntegerField(default=0)),
                ('manager_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hr_business_partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_step', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('pay_frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('SEMI_MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('benefits_eligibility_date', models.DateField(blank=True, null=True)),
                ('benefits_package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('health_insurance_eligible', models.BooleanField(default=False)),
                ('dental_insurance_eligible', models.BooleanField(default=False)),
                ('vision_insurance_eligible', models.BooleanField(default=False)),
                ('retirement_plan_eligible', models.BooleanField(default=False)),
                ('life_insurance_eligible', models.BooleanField(default=False)),
                ('primary_emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_key_employee', models.BooleanField(default=False)),
                ('is_high_potential', models.BooleanField(default=False)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('rehire_eligible', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(default='Employee', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Record',
                'verbose_name_plural': 'Employee Records',
                'db_table': 'employee_record',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('MAILING', 'Mailing'), ('TEMPORARY', 'Temporary')], max_length=50)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='hrm.employeerecord')),
            ],
            options={
                'verbose_name': 'Employee Address',
                'verbose_name_plural': 'Employee Addresses',
                'db_table': 'employee_address',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='hrm.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hrm.employeerecord')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['company_code', 'employee_number'], name='idx_company_employee'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['company_code', 'is_active'], name='idx_employee_company_active'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['department_name', 'is_active'], name='idx_dept_active'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['position_title', 'is_active'], name='idx_position_active'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['hire_date'], name='idx_hire_date'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_name'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['work_email'], name='idx_work_email'),
        ),
        migrations.AddIndex(
            model_name='employeeaddress',
            index=models.Index(fields=['employee', 'address_type'], name='idx_employee_type'),
        ),
        migrations.AddIndex(
            model_name='employeeaddress',
            index=models.Index(fields=['is_primary'], name='idx_primary'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company_code', 'is_active'], name='idx_dept_company_active'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_code'], name='idx_dept_code'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='idx_parent_dept'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company_code', 'name')},
        ),
    ]
