# Generated by Django 5.1.2 on 2026-01-03 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('employee_id', models.UUIDField()),
                ('position_id', models.UUIDField()),
                ('organizational_unit_id', models.UUIDField()),
                ('created_by_user_id', models.UUIDField()),
                ('updated_by_user_id', models.UUIDField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('acting', 'Acting'), ('interim', 'Interim')], max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reports_to_employee_id', models.UUIDField(blank=True, null=True)),
                ('dotted_line_reports_to', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('transferred', 'Transferred')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Position',
                'verbose_name_plural': 'Employee Positions',
                'db_table': 'hr_employee_positions',
                'indexes': [models.Index(fields=['company_id', 'employee_id'], name='idx_emp_pos_employee'), models.Index(fields=['company_id', 'position_id'], name='idx_emp_pos_position'), models.Index(fields=['company_id', 'organizational_unit_id'], name='idx_emp_pos_org'), models.Index(fields=['company_id', 'is_primary'], name='idx_emp_pos_primary')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('created_by_user_id', models.UUIDField()),
                ('updated_by_user_id', models.UUIDField(blank=True, null=True)),
                ('parent_unit_id', models.UUIDField(blank=True, null=True)),
                ('manager_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('company', 'Company'), ('division', 'Division'), ('department', 'Department'), ('team', 'Team'), ('section', 'Section'), ('cost_center', 'Cost Center'), ('business_unit', 'Business Unit')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cost_center_code', models.CharField(blank=True, max_length=50)),
                ('budget_owner_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizational Unit',
                'verbose_name_plural': 'Organizational Units',
                'db_table': 'hr_organizational_units',
                'indexes': [models.Index(fields=['company_id', 'parent_unit_id'], name='idx_org_hierarchy'), models.Index(fields=['company_id', 'unit_type'], name='idx_org_type'), models.Index(fields=['company_id', 'is_active'], name='idx_org_active'), models.Index(fields=['company_id', 'level'], name='idx_org_level')],
                'constraints': [models.UniqueConstraint(fields=('company_id', 'code'), name='uk_org_unit_code')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('organizational_unit_id', models.UUIDField()),
                ('created_by_user_id', models.UUIDField()),
                ('updated_by_user_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('position_code', models.CharField(max_length=50)),
                ('job_grade', models.CharField(max_length=50)),
                ('job_family', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('temporary', 'Temporary')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager_position', models.BooleanField(default=False)),
                ('headcount', models.IntegerField(default=1)),
                ('filled_count', models.IntegerField(default=0)),
                ('vacancy_count', models.IntegerField(default=0)),
                ('reports_to_position_id', models.UUIDField(blank=True, null=True)),
                ('dotted_line_reports_to', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'hr_positions',
                'indexes': [models.Index(fields=['company_id', 'organizational_unit_id'], name='idx_pos_org'), models.Index(fields=['company_id', 'is_active'], name='idx_pos_active'), models.Index(fields=['company_id', 'job_grade'], name='idx_pos_grade')],
                'constraints': [models.UniqueConstraint(fields=('company_id', 'position_code'), name='uk_position_code')],
            },
        ),
    ]
