# Generated by Django 5.1.2 on 2026-01-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_employeeposition_organizationalunit_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationalunit',
            name='uk_org_unit_code',
        ),
        migrations.RemoveConstraint(
            model_name='position',
            name='uk_position_code',
        ),
        migrations.RemoveIndex(
            model_name='employeeposition',
            name='idx_emp_pos_employee',
        ),
        migrations.RemoveIndex(
            model_name='employeeposition',
            name='idx_emp_pos_position',
        ),
        migrations.RemoveIndex(
            model_name='employeeposition',
            name='idx_emp_pos_org',
        ),
        migrations.RemoveIndex(
            model_name='employeeposition',
            name='idx_emp_pos_primary',
        ),
        migrations.RemoveIndex(
            model_name='organizationalunit',
            name='idx_org_hierarchy',
        ),
        migrations.RemoveIndex(
            model_name='organizationalunit',
            name='idx_org_type',
        ),
        migrations.RemoveIndex(
            model_name='organizationalunit',
            name='idx_org_active',
        ),
        migrations.RemoveIndex(
            model_name='organizationalunit',
            name='idx_org_level',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='idx_pos_org',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='idx_pos_active',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='idx_pos_grade',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='organizationalunit',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='company_id',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='company_code',
            field=models.CharField(db_index=True, default='001', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='company_code',
            field=models.CharField(db_index=True, default='001', max_length=10),
        ),
        migrations.AddField(
            model_name='position',
            name='company_code',
            field=models.CharField(db_index=True, default='001', max_length=10),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['company_code', 'employee_id'], name='idx_emp_pos_employee'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['company_code', 'position_id'], name='idx_emp_pos_position'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['company_code', 'organizational_unit_id'], name='idx_emp_pos_org'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['company_code', 'is_primary'], name='idx_emp_pos_primary'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company_code', 'parent_unit_id'], name='idx_org_hierarchy'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company_code', 'unit_type'], name='idx_org_type'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company_code', 'is_active'], name='idx_org_active'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company_code', 'level'], name='idx_org_level'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company_code', 'organizational_unit_id'], name='idx_pos_org'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company_code', 'is_active'], name='idx_pos_active'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company_code', 'job_grade'], name='idx_pos_grade'),
        ),
        migrations.AddConstraint(
            model_name='organizationalunit',
            constraint=models.UniqueConstraint(fields=('company_code', 'code'), name='uk_org_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('company_code', 'position_code'), name='uk_position_code'),
        ),
    ]
