# Generated by Django 5.1.2 on 2026-01-04 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_remove_organizationalunit_uk_org_unit_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('maiden_name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('CIVIL_PARTNERSHIP', 'Civil Partnership')], max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('personal_phone', models.CharField(blank=True, max_length=50)),
                ('work_phone_extension', models.CharField(blank=True, max_length=10)),
                ('home_address_line_1', models.CharField(blank=True, max_length=500)),
                ('home_address_line_2', models.CharField(blank=True, max_length=500)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('home_state', models.CharField(blank=True, max_length=100)),
                ('home_postal_code', models.CharField(blank=True, max_length=20)),
                ('home_country', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('COMPANY', 'Company Only'), ('DEPARTMENT', 'Department Only'), ('PRIVATE', 'Private')], default='COMPANY', max_length=20)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hrm.employeerecord')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'db_table': 'employee_profile',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('CONTRACT', 'Contract'), ('OFFER_LETTER', 'Offer Letter'), ('ID_PROOF', 'ID Proof'), ('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('WORK_PERMIT', 'Work Permit'), ('CERTIFICATION', 'Certification'), ('EDUCATION', 'Education'), ('TRAINING', 'Training'), ('PERFORMANCE', 'Performance Review'), ('OTHER', 'Other')], max_length=100)),
                ('document_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.employeeprofile')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'db_table': 'employee_document',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_category', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('years_experience', models.IntegerField(default=0)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hrm.employeeprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'db_table': 'employee_skill',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, default='001', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='hrm.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_category',
            },
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['company_code', 'employee'], name='idx_profile_employee'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['company_code', 'profile_visibility'], name='idx_profile_visibility'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee', 'is_active'], name='idx_employee_active'),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(fields=('company_code', 'employee'), name='uk_profile_employee'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['company_code', 'employee'], name='idx_doc_employee'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['company_code', 'document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'is_active'], name='idx_doc_active'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['company_code', 'employee'], name='idx_skill_employee'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['company_code', 'skill_category'], name='idx_skill_category'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['employee', 'is_active'], name='idx_skill_active'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['company_code', 'is_active'], name='idx_skill_cat_active'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['parent_category'], name='idx_parent_category'),
        ),
        migrations.AlterUniqueTogether(
            name='skillcategory',
            unique_together={('company_code', 'name')},
        ),
    ]
