# Generated by Django 5.1.2 on 2026-01-11 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_applicationanswer_applicationcandidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(help_text="Used as viewId in Frontend (e.g., 'HRM_EMPLOYEE_MASTER')", max_length=100, unique=True)),
                ('menu_name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], max_length=50)),
                ('applicable_toolbar_config', models.CharField(default='NRQFX', help_text="Config string for this page. Example: 'NRQFX' (New, Refresh, Search, Filter, Exit)", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'hrm_menu_item',
                'ordering': ['module', 'menu_name'],
            },
        ),
        migrations.CreateModel(
            name='ERPToolbarControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], max_length=50, unique=True)),
                ('master_toolbar_string', models.CharField(default='NESCKVPMRDXQF IOLBUGTJ HZAW?', help_text='Full superset of all available toolbar actions', max_length=100)),
            ],
            options={
                'verbose_name': 'Toolbar Control',
                'verbose_name_plural': 'Toolbar Controls',
                'db_table': 'hrm_toolbar_control',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'hrm_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolbar_override', models.CharField(blank=True, help_text="Override string for specific roles (e.g., restricted users cannot Delete 'D')", max_length=100, null=True)),
                ('override_enabled', models.BooleanField(default=False, help_text='Enable this override for the specified role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.erpmenuitem')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'hrm_role_permission',
                'unique_together': {('role', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'hrm_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
