# Generated by Django 5.1.2 on 2026-01-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_erpmenuitem_erptoolbarcontrol_role_rolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmenuitem',
            name='app',
            field=models.CharField(choices=[('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], default='HRM', help_text='Application/Module this menu belongs to', max_length=50),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='menu_type',
            field=models.CharField(choices=[('M', 'Master'), ('T', 'Transaction'), ('D', 'Dashboard'), ('R', 'Report'), ('C', 'Configuration'), ('S', 'Setup'), ('U', 'Utility'), ('Q', 'Query'), ('W', 'Workflow'), ('A', 'Analytics')], default='M', help_text='Type of menu item', max_length=10),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='submodule',
            field=models.CharField(blank=True, help_text='Submodule or subcategory within the application', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='erpmenuitem',
            name='toolbar_config',
            field=models.CharField(default='NRQFX', help_text="Toolbar configuration string for this page. Example: 'NRQFX' (New, Refresh, Search, Filter, Exit)", max_length=100),
        ),
        migrations.AlterField(
            model_name='erpmenuitem',
            name='applicable_toolbar_config',
            field=models.CharField(default='NRQFX', help_text='Legacy field - use toolbar_config instead', max_length=100),
        ),
        migrations.AlterField(
            model_name='erpmenuitem',
            name='module',
            field=models.CharField(choices=[('FMS', 'Financial Management'), ('HRM', 'Human Resources'), ('CRM', 'Customer Relationship Management')], default='HRM', help_text='Module classification for organization', max_length=50),
        ),
    ]
