# Generated by Django 5.1.2 on 2026-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_add_enhanced_menu_item_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmenuitem',
            name='menu_type',
            field=models.CharField(choices=[('MST-S', 'Simple Master'), ('MST-M', 'Medium Master'), ('MST-C', 'Complex Master'), ('TXN-S', 'Simple Transaction'), ('TXN-M', 'Medium Transaction'), ('TXN-C', 'Complex Transaction'), ('M', 'Master (Legacy)'), ('T', 'Transaction (Legacy)'), ('D', 'Dashboard'), ('R', 'Report'), ('C', 'Configuration'), ('S', 'Setup'), ('U', 'Utility'), ('Q', 'Query'), ('W', 'Workflow'), ('A', 'Analytics')], default='M', help_text='Type of menu item based on template classification', max_length=10),
        ),
    ]
