# Generated by Django 5.1.2 on 2026-01-12 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_erpmenuitem_menu_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('track_creates', models.BooleanField(default=True)),
                ('track_updates', models.BooleanField(default=True)),
                ('track_deletes', models.BooleanField(default=True)),
                ('track_views', models.BooleanField(default=False)),
                ('tracked_fields', models.JSONField(default=list)),
                ('excluded_fields', models.JSONField(default=list)),
                ('retention_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Configuration',
                'verbose_name_plural': 'Audit Configurations',
                'db_table': 'hrm_audit_config',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=50)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'db_table': 'hrm_audit_trail',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'model_id'], name='hrm_audit_t_model_n_6b9fe6_idx'), models.Index(fields=['company_code', 'timestamp'], name='hrm_audit_t_company_d87727_idx'), models.Index(fields=['user', 'timestamp'], name='hrm_audit_t_user_id_8818af_idx'), models.Index(fields=['action', 'timestamp'], name='hrm_audit_t_action_85698e_idx')],
            },
        ),
    ]
