# Generated by Django 5.1.2 on 2026-01-13 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_audittrailconfiguration_audittrail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_name', models.CharField(max_length=200)),
                ('path_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_weeks', models.IntegerField(default=4)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('prerequisites', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courselearningpath_company', to='hrm.company')),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'db_table': 'hr_learning_paths',
                'ordering': ['difficulty_level', 'path_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endorsement_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('endorsement_text', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_endorsement_company', to='hrm.company')),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_endorsement_endorser', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_endorsement_profile', to='hrm.employeeprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_endorsement_skill', to='hrm.employeeskill')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_endorsement_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Endorsement',
                'verbose_name_plural': 'Profile Endorsements',
                'db_table': 'hr_profile_endorsements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileViewAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ADMIN', 'Admin')], default='SELF', max_length=20)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_access_company', to='hrm.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_access_profile', to='hrm.employeeprofile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_access_viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile View Access',
                'verbose_name_plural': 'Profile View Access',
                'db_table': 'hr_profile_view_access',
            },
        ),
        migrations.CreateModel(
            name='ProfileViewSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_public_profiles', models.BooleanField(default=False)),
                ('allow_skill_endorsements', models.BooleanField(default=True)),
                ('allow_profile_sharing', models.BooleanField(default=True)),
                ('default_profile_visibility', models.CharField(choices=[('private', 'Private - HR and managers only'), ('team', 'Team - Direct team members'), ('department', 'Department level'), ('company', 'Company level'), ('public', 'Public to all employees')], default='private', max_length=20)),
                ('enable_profile_analytics', models.BooleanField(default=True)),
                ('enable_skill_gap_analysis', models.BooleanField(default=True)),
                ('enable_career_pathing', models.BooleanField(default=True)),
                ('notify_profile_updates', models.BooleanField(default=True)),
                ('notify_endorsements', models.BooleanField(default=True)),
                ('notify_profile_views', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_settings_company', to='hrm.company')),
            ],
            options={
                'verbose_name': 'Profile View Settings',
                'verbose_name_plural': 'Profile View Settings',
                'db_table': 'hr_profile_view_settings',
            },
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.AddIndex(
            model_name='courselearningpath',
            index=models.Index(fields=['company', 'is_active'], name='idx_lp_active'),
        ),
        migrations.AddIndex(
            model_name='profileendorsement',
            index=models.Index(fields=['company', 'profile', 'skill'], name='idx_endorsement_profile_skill'),
        ),
        migrations.AddIndex(
            model_name='profileendorsement',
            index=models.Index(fields=['company', 'endorser'], name='idx_endorsement_endorser'),
        ),
        migrations.AddIndex(
            model_name='profileendorsement',
            index=models.Index(fields=['company', 'is_verified'], name='idx_endorsement_verified'),
        ),
        migrations.AddIndex(
            model_name='profileviewaccess',
            index=models.Index(fields=['company', 'profile'], name='idx_profile_view_profile'),
        ),
        migrations.AddIndex(
            model_name='profileviewaccess',
            index=models.Index(fields=['company', 'viewer'], name='idx_profile_view_viewer'),
        ),
        migrations.AlterUniqueTogether(
            name='profileviewaccess',
            unique_together={('company', 'profile', 'viewer')},
        ),
    ]
