# Generated by Django 5.1.2 on 2026-01-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_courselearningpath_profileendorsement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Organization hierarchy level (0=CEO, 1=Direct reports, etc.)'),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hrm.employeerecord'),
        ),
    ]
