# Generated by Django 5.2.9 on 2026-01-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_employeerecord_hierarchy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerecord',
            name='manager_name',
        ),
    ]
